class ErrorCodes:
    AUTH_REQUIRED = "AUTH_REQUIRED"
    USERNAME_REQUIRED = "USERNAME_REQUIRED"
    PERMISSION_DENIED = "PERMISSION_DENIED"
    CHAT_FORBIDDEN = "CHAT_FORBIDDEN"
    RATE_LIMITED = "RATE_LIMITED"
    ROOM_NOT_FOUND = "ROOM_NOT_FOUND"
    ROOM_EXPIRED = "ROOM_EXPIRED"
