# Generated by Django 4.2.10 on 2026-02-02 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rooms", "0002_roomplaybackstate"),
    ]

    operations = [
        migrations.AddField(
            model_name="room",
            name="host_disconnected_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
