# Generated by Django 4.2.10 on 2026-02-06 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rooms", "0003_room_host_disconnected_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="room",
            name="state",
            field=models.CharField(
                choices=[
                    ("CREATED", "Created"),
                    ("LIVE", "Live"),
                    ("GRACE", "Grace"),
                    ("EXPIRED", "Expired"),
                    ("DELETED", "Deleted"),
                ],
                db_index=True,
                default="CREATED",
                max_length=16,
            ),
        ),
    ]
