# Generated by Django 4.2.10 on 2026-02-11 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rooms", "0005_watchprogress"),
    ]

    operations = [
        migrations.AddField(
            model_name="watchprogress",
            name="completed",
            field=models.BooleanField(default=False),
        ),
    ]