# Generated by Django 4.2.10 on 2026-02-14 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rooms", "0006_watchprogress_completed"),
    ]

    operations = [
        migrations.AddField(
            model_name="roomplaybackstate",
            name="version",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
