# Generated by Django 4.2.10 on 2026-05-27 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rooms", "0007_roomplaybackstate_version"),
    ]

    operations = [
        migrations.AddField(
            model_name="room",
            name="genre",
            field=models.CharField(
                choices=[
                    ("Movies", "Movies"),
                    ("Series", "Series"),
                    ("Anime", "Anime"),
                    ("Sports", "Sports"),
                    ("Music", "Music"),
                    ("Gaming", "Gaming"),
                    ("Documentary", "Documentary"),
                    ("Other", "Other"),
                ],
                default="Other",
                max_length=20,
            ),
        ),
    ]
